config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'off' => 'static_pages#off'

  get 'on' => 'static_pages#on'

  get 'about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    copyright-2016
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Project Demo", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Log in",'#'  %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | Project Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'my_script'%>
  <%= csrf_meta_tags %>
</head>
<body>
     <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<head>

</head>
<body>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
	<style>
.center {
    margin: auto;
    width: 60%;
    border: 3px solid #73AD21;
    padding: 10px;
}
</style>
</head>
<body>
<h1>Sri Subramanya College of Engineering and Technology, Palani</h1>
<h3>Department of Electronics and Communication and Engineering</h3>
<h4>AN INTELLIGENT SELF  LEARNING SYSTEM FOR HOME AUTOMATION USING IOT
</h4>
<p><u>A Project By</u></p>
<div style = "margin-bottom: 50px;margin-left: auto; margin-right: auto;width: 18%">
<ul><li>VIGNESHWARAN S</li>
<li>SUKUMAR K</li>
<li>SATHEESH KUMAR M</li>
<li>SATHAM HUSSIAN A</li>
</ul>
</div>

<p>
<%= link_to "Click Here To Proceed", on_path, class: "btn btn-lg btn-primary" %></p>
</body>
</html>

app/views/static_pages/off.html.erb
<% provide(:title, "Off")%>
<!DOCTYPE html>
<html>
<head></head>
<body>
<h3>Remote switch controller using IoT technology</h3>
<br>
<br><br><br><br><br>
<section style="text-align: center"><%= link_to image_tag("off.png", alt: "Off"), on_path%>
</section>


</body>
</html>

app/views/static_pages/on.html.erb
<% provide(:title, "On")%>
<!DOCTYPE html>
<html>
<head></head>
<body>
<h3>Remote switch controller using IoT technology</h3>
<br>
<br><br><br><br><br>
<section style="text-align: center"><%= link_to image_tag("on.png", alt: "On",onclick: changeImage(1)), off_path%>
</section>


</body>
</html>